# Generated by Django 4.1.3 on 2022-12-10 04:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0014_alter_user_profile_photo_alter_user_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='campus_ambassador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=13)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('college_name', models.CharField(blank=True, default='IIT Patna', max_length=150, null=True)),
                ('college_city', models.CharField(blank=True, default='Patna', max_length=150, null=True)),
                ('refferal_code', models.CharField(blank=True, max_length=150, null=True)),
                ('profile_photo', models.ImageField(blank=True, default='static/images.jpeg', null=True, upload_to='static/profile_photo')),
                ('age', models.SmallIntegerField(blank=True, default=19, null=True)),
                ('intrests', models.CharField(blank=True, choices=[('intrest1', 'Intrest 1'), ('intrest2', 'Intrest 2'), ('intrest3', 'Intrest 3')], max_length=150, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('others', 'Others'), ('rather_not_say', 'Rather not say')], default='rather_not_say', max_length=20)),
                ('score', models.IntegerField(default=0)),
                ('validation', models.BooleanField(default=False)),
                ('instagram_id', models.CharField(blank=True, max_length=255, null=True)),
                ('facebook_id', models.CharField(blank=True, max_length=255, null=True)),
                ('linkdin_id', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter_id', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_birth', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('time_of_registration', models.DateTimeField(auto_now_add=True)),
                ('anwesha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
