# Generated by Django 4.1.3 on 2022-12-15 04:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CA', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus_ambassador',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, default=datetime.datetime.utcnow, null=True),
        ),
    ]
