# Generated by Django 4.1.2 on 2022-12-21 08:00

import anwesha.storage_backend
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CA", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="campus_ambassador",
            options={
                "verbose_name": "Campus Ambassador",
                "verbose_name_plural": "Campus Ambassadors",
            },
        ),
        migrations.AlterField(
            model_name="campus_ambassador",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=anwesha.storage_backend.ProfileImageStorage,
                upload_to="",
            ),
        ),
    ]
