# Generated by Django 4.1.5 on 2026-01-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CA', '0002_alter_campus_ambassador_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus_ambassador',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/profile'),
        ),
    ]
