# Generated by Django 4.1.3 on 2022-12-15 04:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CA', '0002_alter_campus_ambassador_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus_ambassador',
            name='date_of_birth',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 12, 15, 4, 17, 35, 410859, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
