# Generated by Django 4.1.2 on 2023-01-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CA', '0004_alter_campus_ambassador_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campus_ambassador',
            name='id',
        ),
        migrations.AddField(
            model_name='campus_ambassador',
            name='ca_id',
            field=models.CharField(default='x', max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AddField(
            model_name='campus_ambassador',
            name='is_loggedin',
            field=models.BooleanField(default=False),
        ),
    ]
