# Generated by Django 4.1.5 on 2025-01-25 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sleek', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
