# Generated by Django 4.1.5 on 2023-03-11 19:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_alter_user_collage_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('organizer', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('prize', models.CharField(default=0, max_length=150)),
                ('registration_fee', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('registration_deadline', models.DateTimeField(blank=True, null=True)),
                ('video', models.URLField(blank=True)),
                ('poster', models.URLField(blank=True)),
                ('tags', models.CharField(blank=True, choices=[('1', 'tech'), ('2', 'cultural'), ('3', 'sports'), ('4', 'gaming'), ('5', 'workshop'), ('6', 'other')], max_length=40)),
                ('max_team_size', models.SmallIntegerField(default=1)),
                ('min_team_size', models.SmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('is_online', models.BooleanField(default=False)),
                ('registration_link', models.URLField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('payment_link', models.URLField(blank=True)),
                ('payment_key', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(default=None, upload_to='static/gallery/')),
                ('type', models.CharField(choices=[('1', 'image'), ('2', 'video')], default='1', max_length=10)),
                ('tags', models.CharField(blank=True, choices=[('1', 'tech'), ('2', 'cultural'), ('3', 'sports'), ('4', 'gaming'), ('5', 'workshop'), ('6', 'other')], max_length=40)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Gallery',
            },
        ),
        migrations.CreateModel(
            name='PayUTxn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mihpayid', models.CharField(blank=True, max_length=100, null=True)),
                ('mode', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('key', models.CharField(blank=True, max_length=100, null=True)),
                ('txnid', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.CharField(blank=True, max_length=100, null=True)),
                ('addedon', models.CharField(blank=True, max_length=100, null=True)),
                ('productinfo', models.CharField(blank=True, max_length=100, null=True)),
                ('firstname', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('field1', models.CharField(blank=True, max_length=100, null=True)),
                ('field2', models.CharField(blank=True, max_length=100, null=True)),
                ('field3', models.CharField(blank=True, max_length=100, null=True)),
                ('field4', models.CharField(blank=True, max_length=100, null=True)),
                ('field5', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('team_name', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_done', models.BooleanField(default=False)),
                ('txnid', models.CharField(blank=True, max_length=100, null=True)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.events')),
                ('leader_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='TeamParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anwesha_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
                ('event_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.events')),
                ('team_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.team')),
            ],
        ),
        migrations.CreateModel(
            name='SoloParicipants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_done', models.BooleanField(default=False)),
                ('order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('anwesha_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
                ('event_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.events')),
            ],
        ),
        migrations.CreateModel(
            name='Payer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('pending', 'Pending')], default='unpaid', max_length=10)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('order_id', models.CharField(max_length=100)),
                ('signature', models.CharField(max_length=100)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('payer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
                ('team_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.team')),
            ],
        ),
    ]
