# Generated by Django 4.1.5 on 2023-01-31 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='add_merch',
            options={},
        ),
        migrations.AlterModelOptions(
            name='order_merch',
            options={},
        ),
        migrations.AlterField(
            model_name='add_merch',
            name='id',
            field=models.AutoField(max_length=4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='add_merch',
            name='image',
            field=models.ImageField(default=None, upload_to='static/merch/'),
        ),
        migrations.AlterField(
            model_name='add_merch',
            name='size',
            field=models.CharField(choices=[('1', 'S'), ('2', 'M'), ('3', 'L'), ('4', 'XL'), ('5', 'XXL'), ('6', 'XXXL')], max_length=50),
        ),
        migrations.AlterField(
            model_name='order_merch',
            name='size',
            field=models.CharField(choices=[('1', 'S'), ('2', 'M'), ('3', 'L'), ('4', 'XL'), ('5', 'XXL'), ('6', 'XXXL')], max_length=50),
        ),
    ]
