# Generated by Django 4.1.2 on 2022-12-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("event", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="events",
            options={
                "ordering": ["start_time"],
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
            },
        ),
        migrations.AlterModelOptions(
            name="gallery",
            options={"verbose_name": "Gallery", "verbose_name_plural": "Gallery"},
        ),
        migrations.AddField(
            model_name="events",
            name="min_team_size",
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
