# Generated by Django 4.1.5 on 2023-01-31 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('event', '0002_alter_add_merch_options_alter_order_merch_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_merch',
            old_name='merch_id',
            new_name='merch_title',
        ),
        migrations.RemoveField(
            model_name='add_merch',
            name='id',
        ),
        migrations.RemoveField(
            model_name='add_merch',
            name='timestamp',
        ),
        migrations.AlterField(
            model_name='add_merch',
            name='title',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='order_merch',
            name='address',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='order_merch',
            name='anwesha_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AlterField(
            model_name='order_merch',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order_merch',
            name='phone',
            field=models.CharField(max_length=13),
        ),
    ]
