# Generated by Django 4.1.5 on 2023-02-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_events_is_active_alter_events_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='min_team_size',
            field=models.SmallIntegerField(default=1),
        ),
    ]
