# Generated by Django 4.1.5 on 2023-03-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payutxn',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
