# Generated by Django 4.1.5 on 2023-01-31 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_rename_merch_id_order_merch_merch_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_merch',
            old_name='phone',
            new_name='phone_no',
        ),
    ]
