# Generated by Django 4.1.5 on 2023-02-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_events_min_team_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='registration_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
