# Generated by Django 4.1.5 on 2023-01-31 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_rename_phone_order_merch_phone_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_merch',
            name='anwesha_id',
        ),
    ]
