# Generated by Django 4.1.5 on 2023-02-22 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_team_teamparticipant_soloparicipants_payer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payer',
            name='team_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.team'),
        ),
    ]
