# Generated by Django 4.1.5 on 2026-01-28 17:15

import anwesha.storage_backend
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_events_add_poster_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='poster_file',
            field=models.ImageField(blank=True, null=True, storage=anwesha.storage_backend.PosterFileStorage(), upload_to=''),
        ),
    ]
