# Generated by Django 4.1.5 on 2023-02-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_alter_payer_team_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payer',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
