# Generated by Django 4.1.5 on 2023-02-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_alter_payer_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='soloparicipants',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
