# Generated by Django 4.1 on 2022-10-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='element',
        ),
        migrations.AddField(
            model_name='gallery',
            name='file',
            field=models.FileField(default=None, upload_to='static/gallery/'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='type',
            field=models.CharField(choices=[('1', 'image'), ('2', 'video')], default='1', max_length=10),
        ),
    ]
