# Generated by Django 4.1.5 on 2023-02-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_soloparicipants_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='events',
            name='registration_link',
            field=models.URLField(blank=True),
        ),
    ]
