# Generated by Django 4.1.5 on 2023-03-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_events_is_online_events_registration_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
