# Generated by Django 4.1.5 on 2023-03-05 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_payutxn_events_payment_key_events_payment_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='txnid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
