# Generated by Django 4.1.5 on 2023-03-06 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_collage_name'),
        ('event', '0012_team_txnid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_merch',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order_merch',
            name='name',
        ),
        migrations.RemoveField(
            model_name='order_merch',
            name='phone_no',
        ),
        migrations.AddField(
            model_name='add_merch',
            name='payment_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order_merch',
            name='anwesha_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
        migrations.AddField(
            model_name='order_merch',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order_merch',
            name='payment_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order_merch',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
