# Generated by Django 4.1.5 on 2023-03-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_remove_order_merch_email_remove_order_merch_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_merch',
            name='size',
            field=models.CharField(max_length=50),
        ),
    ]
