# Generated by Django 4.1.5 on 2023-03-11 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0013_remove_add_merch_size_remove_order_merch_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payutxn',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
