# Generated by Django 4.1.5 on 2023-03-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_alter_add_merch_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_merch',
            name='size',
        ),
        migrations.AlterField(
            model_name='order_merch',
            name='size',
            field=models.CharField(blank=True, choices=[('1', 'S'), ('2', 'M'), ('3', 'L'), ('4', 'XL'), ('5', 'XXL'), ('6', 'XXXL')], max_length=50, null=True),
        ),
    ]
