# Generated by Django 4.1.5 on 2023-03-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_remove_add_merch_size_alter_order_merch_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='payutxn',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
