# Generated by Django 4.1 on 2022-10-11 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0002_remove_participant_team_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='team_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='participant.participant'),
        ),
    ]
