# Generated by Django 4.1 on 2022-10-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0003_participant_team_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='team_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
