# Generated by Django 4.1.5 on 2025-01-25 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_alter_user_profile_photo_alter_user_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='FestPasses',
            fields=[
                ('id', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('transaction_id', models.CharField(max_length=255)),
                ('has_entered', models.BooleanField(default=False)),
                ('payment_done', models.BooleanField(default=False)),
                ('anwesha_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
