# Generated by Django 4.1.5 on 2025-01-26 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0004_soloparicipants_has_entered_and_more'),
        ('user', '0003_alter_user_profile_photo_alter_user_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('event_type', models.CharField(choices=[('solo', 'Solo'), ('team', 'Team')], default='solo', max_length=10)),
                ('atompay_transaction_id', models.CharField(max_length=100)),
                ('bank_transaction_id', models.CharField(max_length=100)),
                ('anwesha_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='user.user')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='event.events')),
            ],
            options={
                'verbose_name': 'Event Registration',
                'verbose_name_plural': 'Event Registrations',
                'unique_together': {('anwesha_id', 'event_id', 'event_type')},
            },
        ),
    ]
