# Generated by Django 4.1.2 on 2023-02-10 09:51

import anwesha.storage_backend
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Multicity_Events',
            fields=[
                ('event_id', models.CharField(max_length=4, unique=True)),
                ('event_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('event_description', models.TextField(default='description coming soon...')),
                ('event_poster', models.ImageField(blank=True, null=True, storage=anwesha.storage_backend.MultiCityStorage, upload_to='')),
                ('event_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Multicity_Participants',
            fields=[
                ('registration_id', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('payment_done', models.BooleanField(default=False)),
                ('organisation_type', models.CharField(choices=[('school', 'School'), ('college', 'College'), ('other', 'Other')], default='college', max_length=20)),
                ('solo_team', models.BooleanField(default=True)),
                ('leader_name', models.CharField(max_length=100)),
                ('leader_email', models.CharField(max_length=100)),
                ('leader_phone_no', models.CharField(max_length=13)),
                ('leader_organisation', models.CharField(max_length=100)),
                ('member_one_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('member_one_email', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('member_one_organisation', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('member_one_phone_no', models.CharField(blank=True, default=None, max_length=13, null=True)),
                ('member_two_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('member_two_email', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('member_two_organisation', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('member_two_phone_no', models.CharField(blank=True, default=None, max_length=13, null=True)),
                ('member_three_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('member_three_email', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('member_three_organisation', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('member_three_phone_no', models.CharField(blank=True, default=None, max_length=13, null=True)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='multicity.multicity_events')),
            ],
        ),
    ]
