# Generated by Django 4.1.5 on 2023-01-28 05:22

import anwesha.storage_backend
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multicity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multicity_events',
            name='event_id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='multicity_events',
            name='event_poster',
            field=models.ImageField(blank=True, null=True, storage=anwesha.storage_backend.MultiCityStorage, upload_to=''),
        ),
    ]
