# Generated by Django 4.1.5 on 2023-01-30 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multicity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multicity_events',
            name='event_id',
            field=models.CharField(max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='multicity_events',
            name='event_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='multicity_participants',
            name='registration_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
