# Generated by Django 4.1.5 on 2026-01-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multicity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multicity_events',
            name='event_poster',
            field=models.ImageField(blank=True, null=True, upload_to='static/multicity'),
        ),
    ]
