# Generated by Django 4.1.5 on 2023-02-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multicity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multicity_participants',
            name='registration_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multicity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multicity_participants',
            name='registration_id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
