# Generated by Django 4.1.5 on 2023-01-28 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multicity', '0002_alter_multicity_events_event_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multicity_events',
            name='event_id',
            field=models.CharField(blank=True, max_length=4, primary_key=True, serialize=False, unique=True),
        ),
    ]
