# Generated by Django 4.1.5 on 2023-01-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multicity', '0003_alter_multicity_events_event_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multicity_events',
            name='event_date',
            field=models.DateTimeField(),
        ),
    ]
