# Generated by Django 4.1.5 on 2023-03-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsors',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sponsors',
            name='sponsor_description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
