# Generated by Django 4.1.2 on 2022-12-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sponsor", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sponsors",
            options={"verbose_name": "Sponsor", "verbose_name_plural": "Sponsors"},
        ),
        migrations.AlterField(
            model_name="sponsors",
            name="sponsor_phone_number",
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
