# Generated by Django 4.1.2 on 2022-12-04 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campus_ambassador", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campus_ambassador",
            name="age",
            field=models.SmallIntegerField(blank=True, default=19, null=True),
        ),
        migrations.AlterField(
            model_name="campus_ambassador",
            name="college_city",
            field=models.CharField(
                blank=True, default="Patna", max_length=150, null=True
            ),
        ),
        migrations.AlterField(
            model_name="campus_ambassador",
            name="college_name",
            field=models.CharField(
                blank=True, default="IIT Patna", max_length=150, null=True
            ),
        ),
        migrations.AlterField(
            model_name="campus_ambassador",
            name="college_state",
            field=models.CharField(
                blank=True, default="Bihar", max_length=150, null=True
            ),
        ),
        migrations.AlterField(
            model_name="campus_ambassador",
            name="date_of_birth",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="campus_ambassador",
            name="degree",
            field=models.CharField(
                blank=True, default="Btech", max_length=150, null=True
            ),
        ),
        migrations.AlterField(
            model_name="campus_ambassador",
            name="years_of_study",
            field=models.DateField(blank=True, null=True),
        ),
    ]
