# Generated by Django 4.1.2 on 2022-12-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True, default="", max_length=13, null=True, unique=True
            ),
        ),
    ]
