# Generated by Django 4.1.2 on 2023-02-10 10:23

import anwesha.storage_backend
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, storage=anwesha.storage_backend.PublicQrStorage, upload_to=''),
        ),
    ]
