# Generated by Django 4.1.5 on 2023-03-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/profile'),
        ),
        migrations.AlterField(
            model_name='user',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='static/qr'),
        ),
    ]
