# Generated by Django 4.1 on 2022-10-05 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_age'),
        ('user', '0002_alter_user_age_alter_user_is_email_verified_and_more'),
    ]

    operations = [
    ]
