# Generated by Django 4.1.2 on 2022-12-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_photo",
            field=models.ImageField(blank=True, null=True, upload_to="static/profile"),
        ),
        migrations.AlterField(
            model_name="user",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="static/qr"),
        ),
    ]
