# Generated by Django 4.1.5 on 2023-03-05 06:39

import anwesha.storage_backend
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_profile_photo_alter_user_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, storage=anwesha.storage_backend.ProfileImageStorage, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, storage=anwesha.storage_backend.PublicQrStorage, upload_to=''),
        ),
    ]
