# Generated by Django 4.1.2 on 2023-03-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_profile_photo_alter_user_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='collage_name',
            field=models.CharField(blank=True, default='IIT Patna', max_length=150, null=True),
        ),
    ]
