# Generated by Django 4.1.2 on 2023-03-15 20:29

import anwesha.storage_backend
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_secret_user_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, storage=anwesha.storage_backend.ProfileImageStorage, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, storage=anwesha.storage_backend.PublicQrStorage, upload_to=''),
        ),
    ]
