# Generated by Django 4.1.5 on 2023-12-28 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_profile_photo_alter_user_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile',
        ),
    ]
