# Generated by Django 4.1.5 on 2023-03-05 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_collage_name'),
        ('user', '0003_alter_user_profile_photo_alter_user_qr_code'),
    ]

    operations = [
    ]
