# Generated by Django 4.1 on 2022-10-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_accomadation_selected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('non-student', 'Non-Student'), ('alumni', 'Alumni')], max_length=11, null=True),
        ),
    ]
