# Generated by Django 4.1.2 on 2023-01-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_profile_photo_alter_user_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_loggedin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('non-student', 'Non-Student'), ('alumni', 'Alumni')], default='student', max_length=11, null=True),
        ),
    ]
