# Generated by Django 4.1.5 on 2026-01-26 23:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_appusers_is_logged_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/profile'),
        ),
        migrations.AlterField(
            model_name='user',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='static/qr'),
        ),
        migrations.CreateModel(
            name='AadhaarDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhaar_number', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Aadhaar number must be exactly 12 digits', regex='^\\d{12}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anwesha_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aadhaar_detail', to='user.user')),
            ],
            options={
                'verbose_name': 'Aadhaar Detail',
                'verbose_name_plural': 'Aadhaar Details',
            },
        ),
    ]
