# Generated by Django 4.1.5 on 2026-01-29 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_profile_photo_alter_user_qr_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='myntraFestival',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='myntraVerified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='myntraVerifiedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
