# Generated by Django 4.1 on 2022-10-06 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_age'),
        ('user', '0006_alter_user_anwesha_id'),
    ]

    operations = [
    ]
