# Generated by Django 4.1 on 2022-10-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0007_merge_0002_alter_user_age_0006_alter_user_anwesha_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="accomadation_selected",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="college_name",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email_id",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="full_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_email_verified",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_profile_completed",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("student", "Student"),
                    ("non-student", "Non-Student"),
                    ("alumni", "Alumni"),
                ],
                max_length=11,
                null=True,
            ),
        ),
    ]
