# Generated by Django 4.1 on 2022-10-20 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0010_alter_user_anwesha_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="accomadation_selected",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="email_id",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="full_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("male", "Male"),
                    ("female", "Female"),
                    ("others", "Others"),
                    ("rather_not_say", "Rather not say"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_profile_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_photo",
            field=models.ImageField(
                blank=True,
                default="static/images.jpeg",
                null=True,
                upload_to="static/profile_photo",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="static/qrcode"),
        ),
        migrations.AlterField(
            model_name="user",
            name="time_of_registration",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
