# Generated by Django 3.2.12 on 2022-10-26 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0011_alter_user_accomadation_selected_alter_user_email_id_and_more"),
        ("user", "0011_auto_20221022_1228"),
    ]

    operations = []
