# Generated by Django 4.1.2 on 2022-10-29 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_user_phone_number'),
        ('user', '0012_merge_20221026_1740'),
    ]

    operations = [
    ]
