# Generated by Django 4.1.2 on 2022-12-20 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0014_alter_user_profile_photo_alter_user_qr_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_locked",
            field=models.BooleanField(default=False),
        ),
    ]
