# Generated by Django 4.1.2 on 2022-12-20 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0015_user_is_locked"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="college_name",
            new_name="collage_name",
        ),
    ]
